---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-repo
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/my-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-repo
  targetNamespace: default
  timeout: 2m0s
  wait: true
